# Generated by Django 4.2.3 on 2023-08-10 08:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_userinfo_delete_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="course",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 8, 10, 8, 47, 41, 184065, tzinfo=datetime.timezone.utc
                ),
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userinfo",
            name="department",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userinfo",
            name="purpose",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 8, 10, 8, 48, 11, 912536, tzinfo=datetime.timezone.utc
                ),
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
