# Generated by Django 4.2.3 on 2023-08-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_course_department_purpose_student_delete_userinfo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="materials",
            field=models.ManyToManyField(blank=True, to="store.material"),
        ),
    ]
